In [1]:
import pandas as pd

In [23]:
# reading data set
data_set = pd.read_csv(r'C:\Users\admin\Desktop\data science\assignment\dataset_Facebook.csv', sep = ';')
data_set.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [11]:

print(data_set.columns)

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [14]:
# divinding the first subset
sub_set_one = data_set[['Post Month', 'Paid']]

In [22]:
print("shape of subset is ", sub_set_one.shape)
print(sub_set_one)

shape of subset is  (500, 2)
     Post Month  Paid
0            12   0.0
1            12   0.0
2            12   0.0
3            12   1.0
4            12   0.0
..          ...   ...
495           1   0.0
496           1   0.0
497           1   0.0
498           1   0.0
499           1   NaN

[500 rows x 2 columns]

In [21]:
# divinding the second subset
sub_set_two = data_set[['Page total likes', 'Type', 'Category']]
print("shape of subset is ", sub_set_two.shape)
print(sub_set_two)

shape of subset is  (500, 3)
     Page total likes    Type  Category
0              139441   Photo         2
1              139441  Status         2
2              139441   Photo         3
3              139441   Photo         2
4              139441   Photo         2
..                ...     ...       ...
495             85093   Photo         3
496             81370   Photo         2
497             81370   Photo         1
498             81370   Photo         3
499             81370   Photo         2

[500 rows x 3 columns]

In [32]:
# merging 
sub_set_three = pd.concat([sub_set_one, sub_set_two ])
print("shape of subset is ", sub_set_three.shape)
sub_set_three.head(10)

shape of subset is  (1000, 5)

   Post Month  Paid  Page total likes Type  Category
0        12.0   0.0               NaN  NaN       NaN
1        12.0   0.0               NaN  NaN       NaN
2        12.0   0.0               NaN  NaN       NaN
3        12.0   1.0               NaN  NaN       NaN
4        12.0   0.0               NaN  NaN       NaN
5        12.0   0.0               NaN  NaN       NaN
6        12.0   1.0               NaN  NaN       NaN
7        12.0   1.0               NaN  NaN       NaN
8        12.0   0.0               NaN  NaN       NaN
9        12.0   0.0               NaN  NaN       NaN

In [39]:
sub_set_three = sub_set_three.sort_values(by = 'Paid', ascending = True)

In [40]:
sub_set_three.transpose()
print("data set after trasnpose is ", sub_set_three.transpose().shape)

data set after trasnpose is  (5, 1000)

In [41]:
sub_set_three.head(10)

     Post Month  Paid  Page total likes Type  Category
0          12.0   0.0               NaN  NaN       NaN
315         6.0   0.0               NaN  NaN       NaN
312         6.0   0.0               NaN  NaN       NaN
311         6.0   0.0               NaN  NaN       NaN
310         6.0   0.0               NaN  NaN       NaN
309         6.0   0.0               NaN  NaN       NaN
308         6.0   0.0               NaN  NaN       NaN
306         6.0   0.0               NaN  NaN       NaN
305         6.0   0.0               NaN  NaN       NaN
304         6.0   0.0               NaN  NaN       NaN

In [34]:
# reshaping
sub_set_four = pd.pivot_table(sub_set_three, index='Paid')

In [38]:
print("data set shape is ", sub_set_four.shape)
sub_set_four.head()

data set shape is  (2, 1)

      Post Month
Paid
0.0     7.088889
1.0     6.949640